name: Build and Push to ECR

on:
  pull_request: 
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID0}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY0}}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          mask-password: "true"

      - name: Build, tag and push API image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: r9l6i0a8
          REPOSITORY: arquisisters
          API_TAG: api-latest
          PRODUCER_TAG: producer-latest
          CONSUMER_TAG: consumer-latest
          WORKER_DASHBOARD_TAG: worker-dashboard-latest
          BROKER_TAG: broker-latest
        run: |
          docker compose build
          docker tag backend-producer:latest $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$PRODUCER_TAG
          docker tag backend-consumer:latest $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$CONSUMER_TAG
          docker tag backend-worker-dashboard:latest $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$WORKER_DASHBOARD_TAG
          docker tag backend-broker:latest $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$BROKER_TAG
          docker tag backend-api:latest $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$API_TAG 
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$PRODUCER_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$CONSUMER_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$WORKER_DASHBOARD_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$BROKER_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$API_TAG
          